### ISSUE TITLE
Add postgresql, mssql and oracle option for APIM 3.0.0 pattern 1

### ISSUE THREAD

**Issue by ctienshi** [wso2/aws-apim#45]
**Description:**
The current APIM 3.0.0 Pattern 1 resources contain only MySQL as a DB option. Add postgresql, mssql and oracle support for Pattern 1.

**Suggested Labels:**
Type/Improvement

**Suggested Assignees:**
@ctienshi 

**Affected Product Version:**
API 3.0.0

**OS, DB, other environment details and versions:**    
DB - Oracle, MSSQL and Postgre

**Comment by VimukthiPerera** [comment]
https://github.com/wso2/aws-apim/pull/47/files
